export const companiesList = [
"noon","https://www.linkedin.com/company/nooncom/",
"Q3 Technologies","https://www.linkedin.com/company/q3-technologies/",
"Oteemo Inc.","https://www.linkedin.com/company/oteemo/",
"Polestar Analytics","https://www.linkedin.com/company/level-ai/",
"CitiusTech","https://www.linkedin.com/company/citiustech/",
"York IE","https://www.linkedin.com/company/york-ie/",
"Rishabh Software","https://www.linkedin.com/company/rishabh-software/",
"Arcadia","https://www.linkedin.com/company/arcadiahq/",
"Emerson","https://www.linkedin.com/company/emerson/",
"Nagarro","https://www.linkedin.com/company/nagarro/",
"Mphasis","https://www.linkedin.com/company/mphasis/",
"ZentrumHub","https://www.linkedin.com/company/zentrumhub/",
"Eastern Enterprise","https://www.linkedin.com/company/eastern-enterprise/",
"RSM US LLP","https://www.linkedin.com/company/rsm-us-llp/",
"Top 10 accounting","https://big4accountingfirms.com/top-10-accounting-firms/",
"Nielsen","https://www.linkedin.com/company/nielsen/",
"Janjaes Tech Solutions","https://www.linkedin.com/company/janjaes-tech-solution/",
"Swiss Re","https://www.linkedin.com/company/swiss-re/",
"Akamai Technologies","https://www.linkedin.com/company/akamai-technologies/",
"Communify Fincentric","https://www.linkedin.com/company/communifyglobal/",
"Polestar Analytics","https://www.linkedin.com/company/polestar-analytics/",
"Collabera","https://www.linkedin.com/company/collabera/",
"Align Techn?","https://www.linkedin.com/company/aligntechne/",
"Sungate Solutions Inc.","https://www.linkedin.com/company/sungate-solutions-inc./",
"Nova Bus","https://www.linkedin.com/company/nova-bus/",
"Enterpret","https://www.linkedin.com/company/enterpret/",
"FluidCloud","https://www.linkedin.com/company/fluidcloud/",
"Straatix Partners","https://www.linkedin.com/company/straatix-partners/",
"Milestone Inc","https://www.linkedin.com/company/milestone-internet-marketing/",
"Novartis","https://www.linkedin.com/company/novartis/",
"Clarivate","https://www.linkedin.com/company/clarivate/",
"Blue Yonder","https://www.linkedin.com/company/blueyonder/",
"SurveyMonkey","https://www.linkedin.com/company/surveymonkey/",
"IT Convergence","https://www.linkedin.com/company/it-convergence/",
"Quick Heal","https://www.linkedin.com/company/quick-heal-technologies-pvt--ltd-/",
"Persistent Systems","https://www.linkedin.com/company/persistent-systems/",
"New Relic","https://www.linkedin.com/company/new-relic-inc-/",
"Mastercard","https://www.linkedin.com/company/mastercard/",
"Target","https://www.linkedin.com/company/target/",
"Visa","https://www.linkedin.com/company/visa/",
"Innovaccer","https://www.linkedin.com/company/innovaccer/",
"Accurate Background","https://www.linkedin.com/company/accurate-background/",
"AthenaHealth","https://www.linkedin.com/company/athenahealth/",
"NAB","https://www.linkedin.com/company/nab/",
"Global Logic","https://www.linkedin.com/company/globallogic/",
"Tower Research Capital","https://www.linkedin.com/company/tower-research-capital/",
"BroadCom","https://www.linkedin.com/company/broadcom/",
"Bank of America","https://www.linkedin.com/company/bank-of-america/",
"Baxter","https://www.linkedin.com/company/baxter-healthcare/",
"Carelon","https://www.linkedin.com/company/carelon-global-solutions-in/",
"Shell Recharge Solution","https://www.linkedin.com/company/shell-recharge-solutions/",
"American Express","https://www.linkedin.com/company/american-express/",
"Blue Yonder","https://www.linkedin.com/company/blueyonder/",
"Quantiphi -","https://www.linkedin.com/company/quantiphi/",
"Honeywell","https://www.linkedin.com/company/honeywell/",
"Happiest Minds","https://www.linkedin.com/company/happiest-minds-technologies/",
"Medplus","https://www.linkedin.com/company/medplusindia/",
"Redbus","https://www.linkedin.com/company/redbus_2/",
"Globant","https://www.linkedin.com/company/globant/",
"Ford","https://www.linkedin.com/company/ford-motor-company/",
"S&P Global","https://www.linkedin.com/company/spglobal/",
"NatWest Group","https://www.linkedin.com/company/natwest-group/",
"UST","https://www.linkedin.com/company/ustglobal/",
"Verizon","https://www.linkedin.com/company/verizon/",
"GE","https://www.linkedin.com/company/ge/",
"WellsFargo","https://www.linkedin.com/company/wellsfargo/",
"Siemens","https://www.linkedin.com/company/siemens/",
"Tek Systems","https://www.linkedin.com/company/teksystems-global-services-india/",
"ADP","https://www.linkedin.com/company/adp/",
"Nutanix","https://www.linkedin.com/company/nutanix/",
"Sprinklr","https://www.linkedin.com/company/sprinklr/",
"Fidelity Investments","https://www.linkedin.com/company/fidelity-investments/",
"Altimetrik","https://www.linkedin.com/company/altimetrik/",
"Arcesium","https://www.linkedin.com/company/arcesium/",
"Razorpay","https://www.linkedin.com/company/razorpay/",
"Providence","https://www.linkedin.com/company/providence-india/",
"Harness","https://www.linkedin.com/company/harnessinc/",
"Splunk","https://www.linkedin.com/company/splunk/",
"MongoDB","https://www.linkedin.com/company/mongodbinc/",
"Bosch","https://www.linkedin.com/company/bosch/",
"Fractal","https://www.linkedin.com/company/fractal-analytics/",
"Thomson Reuters","https://www.linkedin.com/company/thomson-reuters/",
"To the New","https://www.linkedin.com/company/tothenew/",
"Gap inc","https://www.linkedin.com/company/gap-inc-/",
"Experian","https://www.linkedin.com/company/experian/",
"Iqvia","https://www.linkedin.com/company/iqvia/",
"NielsenIQ","https://www.linkedin.com/company/nielseniq/",
"State Street","https://www.linkedin.com/company/state-street/",
"Tavant","https://www.linkedin.com/company/tavant/",
"Amadeus","https://www.linkedin.com/company/amadeus/",
"Ericsson","https://www.linkedin.com/company/ericsson/",
"Genpact","https://www.linkedin.com/company/genpact/",
"Rakuten","https://www.linkedin.com/company/rakuten/",
"Synopsys","https://www.linkedin.com/company/synopsys/",
"Rupyy","https://www.linkedin.com/company/rupyy/",
"Schneider Electric","https://www.linkedin.com/company/schneider-electric/",
"AMD","https://www.linkedin.com/company/amd/",
"Sutherland","https://www.linkedin.com/company/sutherland-global/",
"NTT Data","https://www.linkedin.com/company/ntt-data-americas/",
"Infinite Computer Solutions","https://www.linkedin.com/company/infinite-computer-solutions/",
"Sonata","https://www.linkedin.com/company/sonata-software/",
"Mouri Tech","https://www.linkedin.com/company/mouritech/",
"CGI","https://www.linkedin.com/company/cgi/",
"Expedia","https://www.linkedin.com/company/expedia/",
"Akamai Technologies","https://www.linkedin.com/company/akamai-technologies/",
"Transunion","https://www.linkedin.com/company/transunion/",
"Thoughtworks","https://www.linkedin.com/company/thoughtworks/",
"Tesco","https://www.linkedin.com/company/tesco-bengaluru/",
"Tavant","https://www.linkedin.com/company/tavant/",
"Wissen Technology","https://www.linkedin.com/company/wissen-technology/",
"ITC Infotech","https://www.linkedin.com/company/itc-infotech/",
"Teleperformance","https://www.linkedin.com/company/teleperformance/",
"Societe Generale","https://www.linkedin.com/company/societe-generale/",
"FactSet","https://www.linkedin.com/company/factset/",
"Telstra","https://www.linkedin.com/company/telstra/",
"OpenText","https://www.linkedin.com/company/opentext/",
"Collabera","https://www.linkedin.com/company/collabera-digital/",
"Deutsche Bank","https://www.linkedin.com/company/deutsche-bank/",
"Citi Bank","https://www.linkedin.com/company/citi-india/",
"World Line","https://www.linkedin.com/company/worldlineglobal/",
"Morgan Stanley","https://www.linkedin.com/company/morgan-stanley/",
"Clarivate","https://www.linkedin.com/company/clarivate/",
"Barclays","https://www.linkedin.com/company/barclays-bank/",
"Fedex","https://www.linkedin.com/company/fedex/",
"Tredence Inc.","https://www.linkedin.com/company/tredence/",
"Sanofi","https://www.linkedin.com/company/sanofi/",
"Demandbase","https://www.linkedin.com/company/demandbase/",
"New Relic","https://www.linkedin.com/company/new-relic-inc-/",
"Postman","https://postman.com",
"Shopify","https://shopify.com",
"Stripe","https://stripe.com",
"Spotify","https://spotify.com",
"AFFORDMATE","http://www.affordmate.com",
"Xapo Bank","http://www.xapobank.com",
"Symetra","http://www.symetra.com",
"Docker Inc","https://lnkd.in/gfX5-pQG",
"Upwork","https://lnkd.in/gt4HYmd6",
"Platform.sh","https://platform.sh",
"Trident Digitech Services","https://www.linkedin.com/company/trident-digitech-services/",
]